name: Good morning!

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Every 8 AM SGT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Send sticker
        run: |-
          pip install -r requirements.txt
          python morning.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT: ${{ secrets.CHAT }}